feat: add clean resources action
hipagesgroup/actions pull request #43
Opened 2022-12-12 03:58 UTC by WarmVissarutRonaldoDude

### Description

create composite action that we can reuse anywhere for clean up resources after PR has been deleted/merged.

- delete images from GHCR.
- delete k8s resources immediately instead of wait for 24hrs.

2022-12-12 04:02 UTC, pupudu commented
Looks pretty good to me 🚚  
I will let the @hipagesgroup/platform review the code though

2022-12-12 04:16 UTC, viniciusps commented on clean/action.yaml
> +name: clean
I think `clean` would not be too intuitive 🤔 

what about `cleanup-resources` something like that?

2022-12-12 04:18 UTC, JoshVee commented on clean/action.yaml
> +    required: false
you've got kebab case, snake case _and_ camel case all being used.

standardise on kebab case

2022-12-12 04:18 UTC, JoshVee requested changes
see comments

2022-12-12 04:32 UTC, WarmVissarutRonaldoDude commented on clean/action.yaml
> +    required: false
ah yeah my bad, done.

2022-12-12 04:32 UTC, WarmVissarutRonaldoDude commented on clean/action.yaml
> +name: clean
yup agreed.

2022-12-13 03:16 UTC, WarmVissarutRonaldoDude commented
@viniciusps @JoshVee please help re-review when you guys available, thank you! 🙏

2022-12-13 03:31 UTC, viniciusps commented on cleanup-resources/action.yaml
> +    - name: Delete application from ArgoCD
Sorry but another comment. 
I am not sure if it is valid but should we add any checks around the app name or branch? like just to make sure no one accidentally passes a prod Argo app name and causes an outage?

2022-12-13 03:50 UTC, WarmVissarutRonaldoDude commented on cleanup-resources/action.yaml
> +    - name: Delete application from ArgoCD
hmm should we restrict token to only delete app & resources in `playground` namespace 🤔

2022-12-13 03:53 UTC, WarmVissarutRonaldoDude commented on cleanup-resources/action.yaml
> +    - name: Delete application from ArgoCD
and maybe we can do `argocd app get xxx` and check namespace from that app details 🤔 let me see

2022-12-13 04:51 UTC, WarmVissarutRonaldoDude commented on cleanup-resources/action.yaml
> +    - name: Delete application from ArgoCD
@viniciusps done.

2022-12-13 05:09 UTC, viniciusps commented on cleanup-resources/action.yaml
> +    - name: Delete application from ArgoCD
Awesome. Nice Work 🚀

2022-12-13 05:09 UTC, viniciusps approved these changes

2022-12-14 00:51 UTC, WarmVissarutRonaldoDude commented
Hi! @JoshVee can you help re-review too, thanks!

2023-05-23 04:57 UTC, closed without merging